{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5cd0cb75",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "GO FIRE WALL IS OFF\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://192.168.0.102:8000/ (Press CTRL+C to quit)\n",
      "[2023-05-07 19:52:15,389] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:15] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:16,422] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:16] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:17,466] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:17] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:18,493] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:18] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:19,513] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:19] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:20,562] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:52:20] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:21,604] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:21] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:22,642] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:22] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:23,678] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:23] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:24,716] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:24] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:25,753] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:25] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:26,772] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:52:26] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:27,816] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:27] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:28,841] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:28] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:29,878] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:29] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:30,907] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:30] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:31,945] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:31] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:32,986] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:52:32] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:34,020] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:34] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:35,051] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:35] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:36,086] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:36] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:37,127] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:37] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:38,163] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:38] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:39,193] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:52:39] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:40,229] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:40] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:41,264] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:41] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:42,300] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:42] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:43,339] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:43] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:44,377] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:44] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:45,407] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:52:45] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:46,442] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:46] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:47,478] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:47] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:48,523] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:48] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:49,550] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:49] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:50,577] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:50] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:51,606] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:52:51] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:52,645] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:52] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:53,679] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:53] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:54,705] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:54] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:55,746] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:55] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:56,761] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:56] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:57,801] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:52:57] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:58,837] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:58] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:52:59,874] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:52:59] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:00,911] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:00] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:01,952] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:01] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:02,989] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:02] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:04,018] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.0.179 - - [07/May/2023 19:53:04] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:05,049] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:05] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:06,075] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:06] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:07,113] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:07] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:08,153] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:08] \"GET / HTTP/1.1\" 500 -\n",
      "[2023-05-07 19:53:09,180] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\siebe\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 50, in index\n",
      "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
      "  File \"C:\\Users\\siebe\\AppData\\Local\\Temp/ipykernel_13936/4173717747.py\", line 24, in get_video_stream\n",
      "    server_socket.bind(('192.168.0.179', 8000))\n",
      "OSError: [WinError 10049] The requested address is not valid in its context\n",
      "192.168.0.179 - - [07/May/2023 19:53:09] \"GET / HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "from flask import Flask, Response\n",
    "\n",
    "app = Flask(__name__)\n",
    "print(\"GO FIRE WALL IS OFF\")\n",
    "# Set up OpenCV face detection\n",
    "face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')\n",
    "\n",
    "def detect_faces(frame):\n",
    "    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)\n",
    "    faces = face_cascade.detectMultiScale(gray, 1.3, 5)\n",
    "    for (x,y,w,h) in faces:\n",
    "        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)\n",
    "    return frame\n",
    "\n",
    "# Set up video stream from ESP32\n",
    "def get_video_stream():\n",
    "    import socket\n",
    "    import io\n",
    "    import struct\n",
    "\n",
    "    server_socket = socket.socket()\n",
    "    server_socket.bind(('192.168.0.179', 8000))\n",
    "    server_socket.listen(0)\n",
    "    connection = server_socket.accept()[0].makefile('rb')\n",
    "    try:\n",
    "        while True:\n",
    "            # Read the length of the image as a 32-bit unsigned int. If the\n",
    "            # length is zero, quit the loop\n",
    "            image_len = struct.unpack('<L', connection.read(struct.calcsize('<L')))[0]\n",
    "            if not image_len:\n",
    "                break\n",
    "            # Construct a stream to hold the image data and read the image\n",
    "            # data from the connection\n",
    "            image_stream = io.BytesIO()\n",
    "            image_stream.write(connection.read(image_len))\n",
    "            # Rewind the stream, open it as an image with PIL and do some\n",
    "            # processing on it\n",
    "            image_stream.seek(0)\n",
    "            frame = np.frombuffer(image_stream.getvalue(), dtype=np.uint8)\n",
    "            frame = cv2.imdecode(frame, cv2.IMREAD_COLOR)\n",
    "            frame = detect_faces(frame)\n",
    "    finally:\n",
    "        connection.close()\n",
    "        server_socket.close()\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return Response(get_video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(host='192.168.0.102', port=8000, debug=False) #dit was via 0.0.0.0 maar die pakt alle interfaces\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d3045ed",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72ae8029",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
